package com.munch.exchange;

public interface IEventConstant {
	
	//RATE
	String RATE_ALLTOPICS = "RATE/*";
	String RATE_NEW = "RATE/NEW";
	String RATE_DELETE = "RATE/DELETED";
	String RATE_UPDATE = "RATE/UPDATED";
	String RATE_LOADING = "RATE/LOADING";
	String RATE_LOADED = "RATE/LOADED";
	
	//QUOTE
	String QUOTE_ALLTOPICS = "QUOTE/*";
	String QUOTE_LOADED = "QUOTE/LOADED";
	String QUOTE_UPDATE = "QUOTE/UPDATE";
	
	//HISTORICAL_DATA
	String HISTORICAL_DATA_ALLTOPICS = "HISTORICAL_DATA/*";
	String HISTORICAL_DATA_LOADED = "HISTORICAL_DATA/LOADED";
	String HISTORICAL_DATA_LOADING = "HISTORICAL_DATA/LOADING";
	String HISTORICAL_DATA_UPDATE = "HISTORICAL_DATA/UPDATE";
	String HISTORICAL_DATA_CLEARED = "HISTORICAL_DATA/CLEARED";
	
	
	//OPTIMIZATION
	String OPTIMIZATION_STARTED = "OPTIMIZATION/STARTED";
	String OPTIMIZATION_FINISHED = "OPTIMIZATION/FINISHED";
	String OPTIMIZATION_NEW_BEST_INDIVIDUAL = "OPTIMIZATION/NEW_BEST_INDIVIDUAL";
	String OPTIMIZATION_NEW_STEP = "OPTIMIZATION/NEW_STEP";
	
	String OPTIMIZATION_RESULTS_LOADED = "OPTIMIZATION/RESULTS/LOADED";
	
	//CHART
	String PERIOD_CHANGED = "PERIOD/CHANGED";
	
	
}
